plugins:
  nephio-project:
    plugins:
    - approve
    - assign
    - blunderbuss
    - help
    - heart
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - trigger
    - verify-owners
    - wip
    - retitle
  nephio-project/test-infra:
    plugins:
    - config-updater

external_plugins:
  nephio-project:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request

config_updater:
  maps:
    prow/config/config.yaml:
      name: config
      namespace: prow
    prow/config/plugins.yaml:
      name: plugins
      namespace: prow

approve:
  - repos:
    - nephio-project/nephio-test-prow-project
    - nephio-project/nephio
    - nephio-project/api
    - nephio-project/nephio-example-packages
    - nephio-project/nephio-packages
    - nephio-project/docs
    - nephio-project/free5gc-packages
    - nephio-project/free5gc
    - nephio-project/edge-status-aggregator
    require_self_approval: true
