---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

dependency:
  name: galaxy
  options:
    role-file: ../../../galaxy-requirements.yml
    requirements-file: ../../../galaxy-requirements.yml
driver:
  name: vagrant
lint: |
  set -e
  PATH=${PATH}
  yamllint -c ../../../.yaml-lint.yml .
platforms:
  - name: focal-$POSFIX_NAME
    box: generic/ubuntu2004
    provider_options:
      gui: false
provisioner:
  name: ansible
  env:
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}/../../../playbooks/library
  inventory:
    group_vars:
      all:
        local_dest_directory: /tmp/kpt-molecule-test/nginx
        pkg: package-examples/nginx
        repo_uri: https://github.com/GoogleContainerTools/kpt
        version: v0.9
        context: kind-kind
        kpt_async: 600
        kpt_poll: 5
verifier:
  name: testinfra
