---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Boostrap servers
  hosts: all
  become: true
  pre_tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        timeout: 300
    - name: Update Apt cache
      ansible.builtin.raw: apt-get update --allow-releaseinfo-change
      become: true
      changed_when: false
      when: ansible_distribution == 'Ubuntu'
    - name: Install pip package
      become: true
      ansible.builtin.package:
        name: python3-pip
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install kubernetes python package
      become: true
      ansible.builtin.pip:
        name: kubernetes==33.1.0
  roles:
    - andrewrothstein.kind
    - andrewrothstein.kubectl
    - role: geerlingguy.docker
      become: true
  tasks:
    - name: Unarchive /tmp/kpt.tgz into /usr/local/bin/
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.57/kpt_linux_amd64-1.0.0-beta.57.tar.gz
        dest: /usr/local/bin/
        creates: /usr/local/bin/kpt

    - name: Get k8s clusters
      become: true
      ansible.builtin.command: kind get clusters
      register: kind_get_cluster
      failed_when: (kind_get_cluster.rc not in [0, 1])
      changed_when: false

    - name: Print kind_get_cluster value
      ansible.builtin.debug:
        var: kind_get_cluster

    - name: Create management cluster
      become: true
      ansible.builtin.command: kind create cluster --kubeconfig /tmp/kubeconfig --config=-
      args:
        stdin: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
              image: kindest/node:v1.32.0
              extraMounts:
                - hostPath: /var/run/docker.sock
                  containerPath: /var/run/docker.sock
          {% if lookup('ansible.builtin.env', 'DOCKER_REGISTRY_MIRRORS') %}
          containerdConfigPatches:
            - |-
              [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
                endpoint = {{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_MIRRORS') | from_json }}
          {% endif %}
      when: not 'kind' in kind_get_cluster.stdout
      changed_when: true

    - name: Create .kube directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy root kubeconfig file
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/kubeconfig
        dest: "{{ ansible_user_dir }}/.kube/config"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: '0644'

    - name: Wait for Kind Nodes to become ready
      kubernetes.core.k8s:
        context: "kind-kind"
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: kind-control-plane
        wait: true
        wait_condition:
          type: Ready
          status: true
