---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Deploy free5GC workload
  hosts: vm
  roles:
    - role: kpt
      repo_uri: https://github.com/nephio-project/nephio-example-packages
      local_dest_directory: /tmp
      pkg: cluster-capi-kind
      version: cluster-capi-kind/v2
      context: kind-kind
      namespaces:
        - default
  tasks:
    - name: Wait for machine resources
      become: true
      kubernetes.core.k8s_info:
        context: kind-kind
        api_version: cluster.x-k8s.io/v1beta1
        kind: Machine
      register: machine_list
      until: machine_list | json_query('resources[*].status.phase') | unique == ["Running"]
      retries: 20
      delay: 30
    - name: Wait for kubeadmcontrolplane resources
      become: true
      kubernetes.core.k8s_info:
        context: kind-kind
        api_version: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlane
      register: kubeadmcontrolplane_list
      until: not kubeadmcontrolplane_list | json_query('resources[*].status.initialized') | bool
      retries: 5
      delay: 10
    - name: Get k8s clusters
      become: true
      ansible.builtin.command: kind get clusters
      register: kind_get_cluster
      failed_when: (kind_get_cluster.rc not in [0, 1])
      changed_when: false
    - name: Print kind_get_cluster value
      ansible.builtin.debug:
        var: kind_get_cluster
    - name: Ensure workload has been created
      ansible.builtin.assert:
        that:
          - kind_get_cluster.stdout_lines | length > 1
          - "'workload' in kind_get_cluster.stdout"
