- name: Run playbook
  block:
    - name: "Including vars/defaults.yaml variables"
      ansible.builtin.include_vars: "{{ playbook_dir }}/vars/defaults.yaml"
      any_errors_fatal: true

- name: Validating OS user is defined
  ansible.builtin.assert:
    that:
      - "'os_user' in vars"
    msg: "os_user is required and is not defined."

- name: Validating OS group is defined
  ansible.builtin.assert:
    that:
      - "'os_group' in vars"
    msg: "os_group is required and is not defined."

- name: Validating software versions are defined
  ansible.builtin.assert:
    that:
      - "'microk8s_version' in vars"
      - "'kubectl_version' in vars"
    msg: "you have to define what versions of microk8s and kubectl you want to install"

- name: Import playbook
  ansible.builtin.import_tasks: tasks/deploy_mk8s.yml
